# Generated by Django 4.2.3 on 2024-02-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='User',
        ),
    ]
